/*
 *  @name       黑阔博客RSS列表
 *  @version    1.0
 *  @author     Holger
 *  @blog       http://ursb.org/
 *  @update     2014/11/11
 */

var urls = [
    "http://ursb.org/feed.xml",
    "http://www.freebuf.com/feed",
    "http://www.unhonker.com/feed",
    "http://www.cnxwsec.com/rss.php",
    "http://www.bccsafe.com/?feed=rss2",
    "http://www.hzsvs.cn/feed.php",
    "http://honker90.sinaapp.com/feed",
    "http://www.nxadmin.com/rss",
    "http://www.lshack.cn/?feed=rss2",
    "http://p2j.cn/?feed=rss2",
    "http://0day5.com/feed",
    "http://blog.80host.com/feed",
    "http://www.depycode.com/rss.php",
    "http://ha.cker.in/feed/",
    "http://gov.com.im/rss",
    "http://rices.so/feed",
    "http://bingdao.sinaapp.com/?feed=rss2",
    "http://www.wooyun.org/feeds/public",
    "http://www.exploit-db.com/rss.xml",
    "http://bbs.pediy.com/external.php?type=RSS2",
    "http://3389.in/feed/",
    "http://www.cnseay.com/feed/",
    "http://x95.org/rss.php",
    "http://www.03sec.com/feed",
    "http://phpinfo.me/feed",
    "http://www.xocoder.com/feed",
    "http://fuck.0day5.com/?feed=rss",
    "http://www.leavesongs.com/rss.php",
    "http://www.7c00.org/index.php/feed/",
    "http://www.hackshell.net/blog/index.php/feed/",
    "http://www.marioo.net/feed",
    "http://www.iyan.pw/feed",
    "http://xxooer.info/feed",
    "http://x95.org/rss.php",
    "http://bigtang.org/feed/",
    // "http://www.luxingmin.com/feed/",#无法访问
    "http://www.5iadmin.com/rss.xml",
    "http://www.ineeke.com/feed/",
    "http://itsafe.org/?feed=rss2",
    "http://www.5luyu.cn/rss.php",
    "http://www.91ri.org/feed",
    "http://bobao.360.cn/rss?type=news",
    "http://bobao.360.cn/rss?type=learning",
    "http://taosay.net/index.php/feed/",
    "http://luom.net/feed/",
    "http://parsec.me/feed",
    "https://zhizhe8.net/rss.php",
    "http://www.gulianqiang.com/rss.php",
    "http://x0day.me/feed",
    "http://www.xiaoshuwu.net/feed/",
    "http://blog.aptsec.net/feed",
    "http://www.ijiandao.com/rss",
    "http://www.knowsafe.com/?/feed/",
    "http://www.secpulse.com/feed",
    "http://blog.idf.cn/feed/",
    "http://www.fooying.com/feed/",
    "http://www.0day.cc/feed",
    "http://blog.upx8.com/feed",
    "http://blog.zcnhonker.net/feed",
    "http://www.cnygf.net/feed",
    "http://www.blackeagle.name/rss",
    "http://www.spriteking.com/rss",
    "http://www.myth007.com/rss",
    "http://www.untnt.com/feed/rss",
    "http://foxck.lofter.com/rss",
    "http://www.aqniu.com/feed",
    "http://evilcos.me/?feed=rss2",
    "http://luom.net/feed/"
];